language: php
sudo: false

env:
  global:
    - MIN_PHP=7.0

matrix:
  include:
    - php: "7.0"
    - php: "7.1"
    - php: "7.2"
  fast_finish: true

cache:
  directories:
    - $HOME/.composer/cache/files

before_install:
  - composer self-update

install:
  - composer install

script:
  - ./vendor/bin/phpunit tests
